### ISSUE TITLE
onig-6.9.9 build issue with latest

### ISSUE THREAD

**Issue by clhess** [adamyg/grief#106]
Looks like there is a conflict with the onig-6.9.9 library with the latest and incompatible pointer types

onig-6.9.9/src/regparse.c: In function ‘names_clear’:
onig-6.9.9/src/regparse.c:811:24: error: passing argument 2 of ‘onig_st_foreach’ from incompatiblepointer type [-Wincompatible-pointer-types]
811 |     onig_st_foreach(t, i_free_name_entry, 0);
|                        ^~~~~~~~~~~~~~~~~
|                        |
|                        int (*)(OnigUChar *, NameEntry *, void *) {aka int (*)(unsigned char *, NameEntry *, void *)}
In file included from onig-6.9.9/src/regparse.c:37:
onig-6.9.9/src/st.h:55:31: note: expected ‘int (*)(void)’ but argument is of type ‘int (*)(OnigUChar *, NameEntry *, void *)’ {aka ‘int (*)(unsigned char *, NameEntry *, void *)’}
55 | int st_foreach _((st_table *, int (*)(ANYARGS), st_data_t));
|                               ^~~~~~~~~~~~~~~~
onig-6.9.9/src/st.h:35:18: note: in definition of macro ‘_’
35 | # define _(args) args
|                  ^~~~
onig-6.9.9/src/regparse.c:796:1: note: ‘i_free_name_entry’ declared here
796 | i_free_name_entry(UChar* key, NameEntry* e, void* arg ARG_UNUSED)
| ^~~~~~~~~~~~~~~~~
onig-6.9.9/src/regparse.c: In function ‘onig_foreach_name’:
onig-6.9.9/src/regparse.c:880:24: error: passing argument 2 of ‘onig_st_foreach’ from incompatiblepointer type [-Wincompatible-pointer-types]
880 |     onig_st_foreach(t, i_names, (HashDataType )&narg);
|                        ^~~~~~~
|                        |
|                        int (*)(OnigUChar *, NameEntry *, INamesArg *) {aka int (*)(unsigned char *, NameEntry *, INamesArg *)}
onig-6.9.9/src/st.h:55:31: note: expected ‘int (*)(void)’ but argument is of type ‘int (*)(OnigUChar *, NameEntry *, INamesArg *)’ {aka ‘int (*)(unsigned char *, NameEntry *, INamesArg *)’}
55 | int st_foreach _((st_table *, int (*)(ANYARGS), st_data_t));
|                               ^~~~~~~~~~~~~~~~
onig-6.9.9/src/st.h:35:18: note: in definition of macro ‘_’
35 | # define _(args) args
|                  ^~~~
onig-6.9.9/src/regparse.c:853:1: note: ‘i_names’ declared here
853 | i_names(UChar* key ARG_UNUSED, NameEntry* e, INamesArg* arg)
| ^~~~~~~
onig-6.9.9/src/regparse.c: In function ‘onig_renumber_name_table’:
onig-6.9.9/src/regparse.c:908:24: error: passing argument 2 of ‘onig_st_foreach’ from incompatiblepointer type [-Wincompatible-pointer-types]
908 |     onig_st_foreach(t, i_renumber_name, (HashDataType )map);
|                        ^~~~~~~~~~~~~~~
|                        |
|                        int (*)(OnigUChar *, NameEntry *, GroupNumMap *) {aka int (*)(unsigned char *, NameEntry *, GroupNumMap *)}
onig-6.9.9/src/st.h:55:31: note: expected ‘int (*)(void)’ but argument is of type ‘int (*)(OnigUChar *, NameEntry *, GroupNumMap *)’ {aka ‘int (*)(unsigned char *, NameEntry *, GroupNumMap *)’}
55 | int st_foreach _((st_table *, int (*)(ANYARGS), st_data_t));
|                               ^~~~~~~~~~~~~~~~
onig-6.9.9/src/st.h:35:18: note: in definition of macro ‘_’
35 | # define _(args) args
|                  ^~~~
onig-6.9.9/src/regparse.c:886:1: note: ‘i_renumber_name’ declared here
886 | i_renumber_name(UChar* key ARG_UNUSED, NameEntry* e, GroupNumMap* map)
| ^~~~~~~~~~~~~~~
onig-6.9.9/src/regparse.c: In function ‘callout_name_table_clear’:
onig-6.9.9/src/regparse.c:1393:24: error: passing argument 2 of ‘onig_st_foreach’ from incompatible pointer type [-Wincompatible-pointer-types]
1393 |     onig_st_foreach(t, i_free_callout_name_entry, 0);
|                        ^~~~~~~~~~~~~~~~~~~~~~~~~
|                        |
|                        int (*)(st_callout_name_key *, CalloutNameEntry *, void *)
onig-6.9.9/src/st.h:55:31: note: expected ‘int (*)(void)’ but argument is of type ‘int (*)(st_callout_name_key *, CalloutNameEntry *, void *)’
55 | int st_foreach _((st_table *, int (*)(ANYARGS), st_data_t));
|                               ^~~~~~~~~~~~~~~~
onig-6.9.9/src/st.h:35:18: note: in definition of macro ‘_’
35 | # define _(args) args
|                  ^~~~
onig-6.9.9/src/regparse.c:1377:1: note: ‘i_free_callout_name_entry’ declared here
1377 | i_free_callout_name_entry(st_callout_name_key* key, CalloutNameEntry* e,
| ^~~~~~~~~~~~~~~~~~~~~~~~~
onig-6.9.9/src/regparse.c: In function ‘setup_ext_callout_list_values’:
onig-6.9.9/src/regparse.c:1891:56: error: passing argument 2 of ‘onig_st_foreach’ from incompatible pointer type [-Wincompatible-pointer-types]
1891 |     onig_st_foreach((CalloutTagTable *)ext->tag_table, i_callout_callout_list_set,
|                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
|                                                        |
|                                                        int (*)(OnigUChar *, CalloutTagVal,void *) {aka int (*)(unsigned char *, long int,  void *)}
onig-6.9.9/src/st.h:55:31: note: expected ‘int (*)(void)’ but argument is of type ‘int (*)(OnigUChar *, CalloutTagVal,  void *)’ {aka ‘int (*)(unsigned char *, long int,  void *)’}
55 | int st_foreach _((st_table *, int (*)(ANYARGS), st_data_t));
|                               ^~~~~~~~~~~~~~~~
onig-6.9.9/src/st.h:35:18: note: in definition of macro ‘_’
35 | # define _(args) args
|                  ^~~~
onig-6.9.9/src/regparse.c:1873:1: note: ‘i_callout_callout_list_set’ declared here
1873 | i_callout_callout_list_set(UChar* key, CalloutTagVal e, void* arg)
| ^~~~~~~~~~~~~~~~~~~~~~~~~~
onig-6.9.9/src/regparse.c: In function ‘callout_tag_table_clear’:
onig-6.9.9/src/regparse.c:1939:24: error: passing argument 2 of ‘onig_st_foreach’ from incompatible pointer type [-Wincompatible-pointer-types]
1939 |     onig_st_foreach(t, i_free_callout_tag_entry, 0);
|                        ^~~~~~~~~~~~~~~~~~~~~~~~
|                        |
|                        int (*)(OnigUChar *, CalloutTagVal,  void *) {aka int (*)(unsigned char *, long int,  void *)}
onig-6.9.9/src/st.h:55:31: note: expected ‘int (*)(void)’ but argument is of type ‘int (*)(OnigUChar *, CalloutTagVal,  void *)’ {aka ‘int (*)(unsigned char *, long int,  void *)’}
55 | int st_foreach _((st_table *, int (*)(ANYARGS), st_data_t));
|                               ^~~~~~~~~~~~~~~~
onig-6.9.9/src/st.h:35:18: note: in definition of macro ‘_’
35 | # define _(args) args
|                  ^~~~
onig-6.9.9/src/regparse.c:1929:1: note: ‘i_free_callout_tag_entry’ declared here
1929 | i_free_callout_tag_entry(UChar* key, CalloutTagVal e, void* arg ARG_UNUSED)
| ^~~~~~~~~~~~~~~~~~~~~~~~

**Comment by clhess** [comment]
if i add -Wno-incompatible-pointer-types to the makefile i can get past most of this but then there's 

gcc --param max-inline-insns-single=1200 -pthread -O1 -DNDEBUG  -Wno-sign-compare -Wno-implicit-fallthrough -Wno-deprecated-non-prototype -Wno-incompatible-pointer-types -I. -I/home/chris/SharedFolder/grief/include  -DHAVE_CONFIG_H -DUSE_POSIX_API -DUSE_BINARY_COMPATIBLE_POSIX_API -DONIG_EXTERN=extern  -I./onig-6.9.9/src -o /home/chris/SharedFolder/grief/obj.gcc/release/liboginrx/st.o -c onig-6.9.9/src/st.c
In file included from onig-6.9.9/src/st.c:9:
onig-6.9.9/src/regint.h:229:37: error: conflicting types for ‘onig_st_foreach’; have ‘int(st_table*, int (*)(st_data_t,  st_data_t,  st_data_t), st_data_t)’ {aka ‘int(st_table *, int (*)(long unsigned int,  long unsigned int,  long unsigned int), long unsigned int)’}
229 | #define st_foreach                  onig_st_foreach
|                                     ^~~~~~~~~~~~~~~
onig-6.9.9/src/st.c:459:1: note: in expansion of macro ‘st_foreach’
459 | st_foreach(st_table* table, int (*func)(st_data_t, st_data_t, st_data_t), st_data_t arg)
| ^~~~~~~~~~
onig-6.9.9/src/regint.h:229:37: note: previous declaration of ‘onig_st_foreach’ with type ‘int(st_table *, int (*)(void), st_data_t)’ {aka ‘int(st_table *, int (*)(void), long unsigned int)’}
229 | #define st_foreach                  onig_st_foreach
|                                     ^~~~~~~~~~~~~~~
onig-6.9.9/src/st.h:55:5: note: in expansion of macro ‘st_foreach’
55 | int st_foreach _((st_table *, int (*)(ANYARGS), st_data_t));
|     ^~~~~~~~~~

**Comment by clhess** [comment]
FYI those issues were on Fedora 42

I tried to build on Ubuntu 24.04 just in case Fedora 42 was too new... and i ran into other problems... 
First --with-icu wouldn't work even though i had libuc74 installed
and removing that configure flag i ran into a different build problem

/usr/bin/ranlib /home/chris/grief/lib.gcc/release/libonigrx.a
publishing headers ...
make[3]: Leaving directory '/home/chris/grief/libonigrx'
publishing headers ...
make[2]: Leaving directory '/home/chris/grief/libonigrx'
make -C libtre
make[2]: Entering directory '/home/chris/grief/libtre'
make[3]: Entering directory '/home/chris/grief/libtre'
make[3]: *** No rule to make target 'tre-master/local_includes/tre.h', needed by 'tre.h'.  Stop.
make[3]: Leaving directory '/home/chris/grief/libtre'
make[2]: *** [Makefile:198: source] Error 2
make[2]: Leaving directory '/home/chris/grief/libtre'
make[1]: *** [Makefile:535: lib.gcc/release/libtre] Error 2
make[1]: Leaving directory '/home/chris/grief'
make: *** [Makefile:197: release] Error 2

**Comment by clhess** [comment]
Ok, i guess the unzip didn't work for the tre-master, so i manually did that and was able to get passed that part of the build on ubuntu

**Comment by clhess** [comment]
Also, is there a way to build this statically so i can install it locally on multiple machines without the need for shared libraries and such?

**Comment by clhess** [comment]
So looks like there's a new oniguruma 6.9.10 release that fixes these problems.  i was able to pull in the file fixes i need to get it to compile but i didn't pull in all the updates but at least that does fix my current build issue on Fedora 42

**Comment by clhess** [comment]
Looks like there's an incompatible-pointer-type in the grmandoc build as well
